### ISSUE TITLE
Memory visibility issues

### ISSUE THREAD

**Issue by bensku** [starandserpent/TerraServer#20]
In some cases (Gradle tests), it seems that memory visibility across threads is not working correctly. I managed to fix one (crash-prone) case yesterday, but one more remains. It is not triggered currently, as I've added a load fence, but still: very much troubling.

If strange behaviour manifests in real-life use cases of Terra, it should be checked again. ChunkBufferTest/queueTest

**Comment by Pawlost** [comment]
I think this issue is obsolete. When @deltasquad451 rewrote tests he hasnt noticed anything unusual.
