### ISSUE TITLE
Volatile accesses and cache lines

### ISSUE THREAD

**Issue by bensku** [starandserpent/TerraServer#22]
Unaligned volatile memory access must be hacked to work reliable, which Chronicle-Values does for ints and longs. For other data types this is **not** done; thus, unaligned access is not safe to use for them.

However, some of our data is indeed aligned, but Chronicle-Values does not know that. This might cause unnecessary performance loss and should be benchmarked.

**Comment by Pawlost** [comment]
This is probably not relavant anymore
