### ISSUE TITLE
Generic transport layer is required

### ISSUE THREAD

**Issue by Pilvinen** [starandserpent/TerraServer#28]
We need a generic transport layer, thus:

Terra <--> Transport layer <--> Networking library

So that we do not directly hook up to a networking library from Terra. We are currently using Aeron networking library, but end users might wish to migrate to a different networking library - for any number of reasons - let's not make it unnecessarily difficult for them by hard coding things into Terra.

**Comment by Pawlost** [comment]
We are using Venom as transport layer
