### ISSUE TITLE
Implement octree mesher

### ISSUE THREAD

**Issue by bensku** [starandserpent/TerraServer#3]
Currently octree meshes cannot be generated since #2 is not done anyway. When it is, octree mesher will need to be created immediately.

This is a bit harder than it sounds, as this will require shader changes to have texture work properly with atlas system. If that was not done, octree meshing wouldn't give any performance benefits when compared to chunk meshing.

**Comment by Pawlost** [comment]
I think I made this. It is greedy meshing which works faster for single material id reference. But I am not sure what is meant by octree meshing.
