### ISSUE TITLE
Make terra optimized

### ISSUE THREAD

**Issue by Pawlost** [starandserpent/TerraServer#40]
GOAL:
Pilvinen:

Memory Usage
1) We want a large view distance, ideally that would be 40 kilometers or more. This cannot be achieved without faking it, but nonetheless.
2) 40 km might be a far stretch, therefore 10 km would be a better suited goal.
3) Failing at that we want to have at least 2 km of view distance. This is still pretty good as far as games of this type generally go. Still, it might be difficult to achieve.
4) We need minimum of 1 km view distance to be really viable. Anything below that would be a failure affecting game play and we'd need to reconsider our options.

FPS
FPS target should be at 60 or more matching most common monitor refresh rate for a fluent and responsive game play experience.

30 FPS build
RAM: 8 GB
GPU: gtx 750 ti with 2 gb of VRAM
CPU: i7 2600s

Startup
The game starting should not depend on whether or not the terrain is generated.

**Comment by Pawlost** [comment]
Test for 1000 chunks
OLD
startup: 23 s
fps: 8 - 10
memory: 1 333 MB

NEW
startup: 2 min 20 s
fps: 60 - 80
memory: 1 400 MB

**Comment by Pawlost** [comment]
5.5. 2019
startup: 1 min 5 s
fps: 60 - 80
memory: 175 MB

**Comment by Pilvinen** [comment]
We need better tests. Things that I want to know:

- How long does it take to generate one chunk (that is in touch with air, ie. top chunk) on the average.
- How long does it take to regenerate the mesh when removing/placing a block.
- Memory usage calculated reliably for world data in-program.
- ?

**Comment by Pawlost** [comment]
22. 05. 2019
Without Weltschmerz
startup: 1 min 32 s
memory: 459 MB

With Weltschmerz:
startup: 44 s
Memory: 508 MB

**Comment by Pawlost** [comment]
This issue was moved to our private wiki as "Optimization"
